### ISSUE TITLE
"Reset User Tour" in footer:  request for addition

### ISSUE THREAD

**Issue by JosephKennedy4** [trema-tech/moodle-theme_trema#121]
The link to "reset user tour for this page" could be added to the footer

**Comment by michael-milette** [comment]
It is more than just the link. I added the link back but suspect that there is also some JavaScript missing because the link neither appears in the Trema footer or in the Boost question mark [?] popup.

If I switch to the Boost theme without making any configuration changes, the reset link shows up in the [?] popup.

**Comment by rmady** [comment]
This issue will be resolved in the next major release of Trema. For now, feel free to try the experimental 'dev' branch which includes the fix for this issue.

Kind regards,
Rodrigo Mady
