### ISSUE TITLE
Login bug

### ISSUE THREAD

**Issue by szhukov186** [trema-tech/moodle-theme_trema#14]
Hello. I have a question. When I attempt to login on the front page, the login page doesn't open, apparently nothing happens. It just redirects me again to front page. What sort of promblem can be this?

![Безымянный2](https://user-images.githubusercontent.com/53010213/61385503-2f741c00-a8bb-11e9-8fa7-3c05409da07a.png)

**Comment by rmady** [comment]
We never found what is causing is this issue. 

Can you test again in the recent trema version?

Thanks for the contribution @szhukov186

**Comment by michael-milette** [comment]
Hi @szhukov186 ,

I am using the theme on several Moodle sites from Moodle 3.8 to 3.11 and it works fine for me. 

What version of Trema are you using? I noticed you reported this issue in 2019. Have you tried the latest version?

What version of Moodle are you using? You can find this out by logging into Moodle as an Administrator and going to Site Administration > Notifications. The version number will be near the bottom of the page.

Also, have you perhaps set the Alternate Login URL field in Site Administration > Plugins > Authentication > Manage Authentication?

What is the URL of the Login link? It should be similar to:
https://yourdomain.com/login/index.php

If your Moodle site is in a folder, it should look be similar to:
https://yourdomain.com/foldername/login/index.php

In order to try and reproduce the issue, please indicate which web browser are you using and on which operating system. 

Examples of web browser examples:
- Chrome
- Firefox
- Edge
- Safari

Examples of operating systems:
- Windows
- MacOS (OS X)
- Linux

Finally, have you recently moved your website to a new server or domain name?

Best regards,

Michael Milette
