### ISSUE TITLE
Dropdown menu (html select)

### ISSUE THREAD

**Issue by trevorfurtado** [trema-tech/moodle-theme_trema#19]
Dropdown menu (html select) in quiz cloze questions are huge.

**Comment by trevorfurtado** [comment]
![trema_question_cloze](https://user-images.githubusercontent.com/2752475/73781391-ed36fd00-476e-11ea-95c2-524530c1d555.png)

**Comment by rmady** [comment]
Hello my friend lol

We still having this issue in question preview. 
Please fix this for the world. 
![Captura de tela de 2020-04-14 21-53-58](https://user-images.githubusercontent.com/8494871/79287580-9fd7ba00-7e9a-11ea-90b2-0b01e724e511.png)

**Comment by zbyles** [comment]
Hello
I have newest version of Moodle and Trema, and I still have this issue. As I can see the solution from trevorfurado posted above is already included in code but it doesn't work as expected...

**Comment by michael-milette** [comment]
This issue will be resolved in the next major release of Trema. In the meantime, please feel free to give our experimental 'dev' branch a try. It includes the fix for this issue as well as addressing colour contrast accessibility issues.
<img width="285" alt="image" src="https://github.com/trema-tech/moodle-theme_trema/assets/3808579/391c7df4-f94d-4a79-b63f-37a5c88851a9">

Best regards,

Michael
