### ISSUE TITLE
Trema installation problem

### ISSUE THREAD

**Issue by manujesusmartin** [trema-tech/moodle-theme_trema#42]
Hi, Rodrigo, pleasure to greet you.
I told you about my problem in the Moodle post, I copy it again below:

_I have Moodle version 3.10, I try to install the Trema Release 3.11.0.1 theme with the Install plugin from ZIP file option, and I get an error:
Install external module from ZIP file Validating theme_trema ... Error
[Error] Moodle version required [2020061500]
Installation aborted due to validation error.
I have tried with other previous versions and with all it gives me an error.
What can be the reason?_

You told me you need more details. What you need to know?

Thank you for your answer.

**Comment by rmady** [comment]
Hi @manujesusmartin 

Which version of Moodle are you using? Can you send the build?

Here is an exemplo:
![image](https://user-images.githubusercontent.com/8494871/123817345-730c9880-d8ce-11eb-9f63-bda8b4f29ee7.png)


I just try to install in Moodle 3.10 by .zip and worked. I'm trying to figure out what's happining with you.

**Comment by michael-milette** [comment]
It has been about 1.5 years since the last question but there has been no response. I will assume that the issue has been resolved for currently supported versions of Moodle. I am therefore closing this ticket. If you are still experiencing the issue, please feel free to re-open the ticket.

Best regards,

Michael Milette
