### ISSUE TITLE
Responsive problem on user profile with RTL language

### ISSUE THREAD

**Issue by khashayar-h** [trema-tech/moodle-theme_trema#47]
Hi i have a problem with viewing this dropdown menu and user profile on mobiles.
![image](https://user-images.githubusercontent.com/23610120/131823456-0ef3e5c7-75c8-41ab-9fd5-1c453f0daa29.png)

**Comment by fabiorochafg** [comment]
Hi @xerxes2000 do you have a public site where we could analyse this situation?

**Comment by michael-milette** [comment]
Hi @fabiorochafg ,

You don't need access to a public site. To reproduce this and other issues related to RTL:

1. Install the Arabic language pack in your instance of Moodle.
2. Navigate to the desired page in your own language.
3. Switch language to Arabic.
4. In Chrome developer tools, change the display to iPhone X as seen in @xerxes2000 's screenshot.

It doesn't matter if you cannot read the text, the display issues will be obvious.

For example, the nav drawer moves from the right to the left side of the screen when you open it. As a result, it covers the nav drawer toggle button and you can no longer close it.
![image](https://user-images.githubusercontent.com/3808579/147666070-923cb709-585b-48a1-9b75-09455f971bc1.png)

I noticed that, when displaying the user Profile page (User menu > Profile), Trema will only allow you to reduce the window to about 500-520px which is too wide for many mobile devices. Something is preventing it from going more narrow. I suspect this might be part of the problem.

I was able to reproduce this issue using the most recent version of Trema 3.11.0.4 on Moodle 3.10. This is not an issue using the Boost theme.

Hope this helps. Best regards,

Michael

**Comment by michael-milette** [comment]
Hi @khashayar-h ,

Thank you for your patience. I tested this with the latest experimental dev branch (which should be published soon) and the problem has been resolved. I believe that the issue was the crowded navbar was pushing the rest of the page to be too wide. Anyway, if you can, I would be thankful it if you could give it a try and let me know how it goes for you. 

Please note that this version of the theme is unfortunately not available for Moodle 3.11. It is only compatible with 4.0 to 4.4.

Best regards,

Michael Milette
