### ISSUE TITLE
Site Home page is not responsive

### ISSUE THREAD

**Issue by nunoguerreiro** [trema-tech/moodle-theme_trema#48]
![image](https://user-images.githubusercontent.com/1771943/133909535-b01f8b9f-bd26-4be9-9d2a-1185f833a1a1.png)

**Comment by michael-milette** [comment]
I think the maximum width for this content on the Home (Front) Page is set by design. It is not a bug. Otherwise, it would look quite odd on very wide screens.

Also, the page is responsive. If you make it narrow (e.g. mobile device), it does self-adjust correctly to the new screen width.

Best regards,

Michael Milette

**Comment by rmady** [comment]
As @michael-milette said, this is not a bug.
Thank you @nunoguerreiro for the contribution and have a nice weekend.
