### ISSUE TITLE
Buttons are not displayed correctly in the mail plugin

### ISSUE THREAD

**Issue by lvarnava** [trema-tech/moodle-theme_trema#84]
Hey! Thank you for a great theme.
Buttons are not displayed correctly in the mail plugin.

Moodle 3.9.8+ (Build: 20210723)
local_mail 1.9.10
theme_trema 3.11.0.4

![2021-11-19_21-42-51](https://user-images.githubusercontent.com/32108411/142675400-5209b18d-9715-4dba-9679-4978ed4c51a5.png)

Please help!

**Comment by michael-milette** [comment]
Hi @lvarnava ,

Some themes have more space around the buttons than others, some have bigger fonts. In this case it is padding around the text in the button that is causing the display issue. The pop-up box was not created using a responsive design so the buttons in Trema (and other 3rd party themes) don't fit where they should and end up pushed down. I have seen alignment issues with this Mail plugin in several popular 3rd party themes (not just Trema), either in this popup window or in the dropdown when you click the mail icon in the header.

You can simply fix the issue yourself using a few lines of CSS, or you can contact the author of the local_mail plugin and ask them to address the issues by adding some CSS to better control the way information is displayed. 

If accessibility is important to your organization, this problem is also going to be an issue for people who use accessibility tools to increase the font size. The author might want to consider revising the layout in order to come up with a more responsive design that meets accessibility guidelines.

Out of five themes that I tried, only the core Moodle Boost and Classic themes displayed this plugin 100% correctly everywhere. That said, I am sure this will vary from one theme to the next.

Best regards,

Michael Milette

**Comment by michael-milette** [comment]
Hi @lvarnava ,

Did you have a chance to contact the developer of the Local_Mail plugin? As it has been over a month since my last comment and I did not hear back from you, I will assume that you have resolved the issue. For the benefit of others, please share your solution.

If this is not the case and you believe there is reason enough to re-open this issue, simply indicate what progress you've made.

Best regards,

Michael
